### ISSUE TITLE
Make parameters in onboardingResponse Optional

### ISSUE THREAD

**Issue by Frank-Wiebeler** [DKE-Data/agrirouter-api-java#12]
Depending on the required Gateway Type (REST or MQTT), several parameters are not always set. Could they be made optional to simplify the work with them in Kotlin?

**Comment by d4ndel1on** [comment]
Due to the fact, lateinit var variables are used which are not optional, the library breaks, if no mqtt settings were passed.
Maybe these fields could be changed like following:
`
    lateinit var host: String
    lateinit var port: String
`
to
`
    lateinit var host: String? = null
    lateinit var port: String? = null
`
This example can be found inside ConnectionCriteria class.

**Comment by saschadoemer** [comment]
We'll find a solution for it. Optional parameters are not the best idea, because they would cause a number of <null> checks within the API. Not the best idea, but I understand the problem. For the current state of the API those fields are removed until the MQTT implementation will be part of the API.

Thanks for the report.
